# Generated by Django 5.0.6 on 2024-06-08 09:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "分类",
                "verbose_name_plural": "分类",
                "ordering": ["-updated"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="标题")),
                ("content", models.TextField(blank=True, null=True, verbose_name="正文")),
                (
                    "status",
                    models.CharField(
                        choices=[("d", "草稿"), ("p", "发表")],
                        default="p",
                        max_length=1,
                        verbose_name="文章状态",
                    ),
                ),
                (
                    "published",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        null=True,
                        verbose_name="发布时间",
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.category",
                        verbose_name="类别",
                    ),
                ),
            ],
            options={
                "verbose_name": "文章",
                "verbose_name_plural": "文章",
                "ordering": ["-updated"],
            },
        ),
    ]
