# Generated by Django 5.0.6 on 2024-06-10 07:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_picture_alter_article_options_alter_category_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="picture",
            name="name",
        ),
    ]
