# Generated by Django 5.0.6 on 2024-06-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_alter_picture_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="picture",
            name="name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="标题"
            ),
        ),
        migrations.AlterField(
            model_name="picture",
            name="img",
            field=models.ImageField(
                blank=True, null=True, upload_to="image", verbose_name="图片"
            ),
        ),
    ]
